export const NEIGHBORHOODS = [
  { label: "11 de Noviembre", value: "11 de Noviembre" },
  { label: "13 de junio", value: "13 de junio" },
  { label: "Albornoz", value: "Albornoz" },
  { label: "Alcibia", value: "Alcibia" },
  { label: "Almirante Colón", value: "Almirante Colón" },
  { label: "Alto Bosque", value: "Alto Bosque" },
  { label: "Altos de San Isidro", value: "Altos de San Isidro" },
  { label: "Amberes", value: "Amberes" },
  { label: "Anita", value: "Anita" },
  { label: "Antonio José de Sucre", value: "Antonio José de Sucre" },
  { label: "Armenia", value: "Armenia" },
  { label: "Arroz Barato", value: "Arroz Barato" },
  { label: "Barlovento", value: "Barlovento" },
  { label: "Barrio Chino", value: "Barrio Chino" },
  { label: "Barrio Obrero", value: "Barrio Obrero" },
  { label: "Bellavista", value: "Bellavista" },
  { label: "Blas de Lezo", value: "Blas de Lezo" },
  { label: "Bocagrande", value: "Bocagrande" },
  { label: "Boston", value: "Boston" },
  { label: "Bosquecito", value: "Bosquecito" },
  { label: "Bruselas", value: "Bruselas" },
  { label: "Buenos Aires", value: "Buenos Aires" },
  { label: "Camagüey", value: "Camagüey" },
  { label: "Camilo Torres", value: "Camilo Torres" },
  { label: "Canapote", value: "Canapote" },
  { label: "Castillogrande", value: "Castillogrande" },
  { label: "Cavipetrol", value: "Cavipetrol" },
  { label: "Ceballos", value: "Ceballos" },
  { label: "Centro", value: "Centro" },
  { label: "Chambacú", value: "Chambacú" },
  { label: "Chipre", value: "Chipre" },
  { label: "Chiquinquirá", value: "Chiquinquirá" },
  { label: "Crespo", value: "Crespo" },
  { label: "Crespito", value: "Crespito" },
  { label: "Daniel Lemaitre", value: "Daniel Lemaitre" },
  { label: "El Bosque", value: "El Bosque" },
  { label: "El Cabrero", value: "El Cabrero" },
  { label: "El Campestre", value: "El Campestre" },
  { label: "El Carmen", value: "El Carmen" },
  { label: "El Centro", value: "El Centro" },
  { label: "El Educador", value: "El Educador" },
  { label: "El Espinal", value: "El Espinal" },
  { label: "El Gallo", value: "El Gallo" },
  { label: "El Nazareno", value: "El Nazareno" },
  { label: "El Pozón", value: "El Pozón" },
  { label: "El Prado", value: "El Prado" },
  { label: "El Reposo", value: "El Reposo" },
  { label: "El Recreo", value: "El Recreo" },
  { label: "El Rubí", value: "El Rubí" },
  { label: "El Silencio", value: "El Silencio" },
  { label: "El Socorro", value: "El Socorro" },
  { label: "Escallón Villa", value: "Escallón Villa" },
  { label: "España", value: "España" },
  { label: "Fredonia", value: "Fredonia" },
  { label: "Getsemaní", value: "Getsemaní" },
  { label: "Henequén", value: "Henequén" },
  { label: "Juan XXIII", value: "Juan XXIII" },
  { label: "Jorge Eliecer Gaitán", value: "Jorge Eliecer Gaitán" },
  { label: "José Antonio Galán", value: "José Antonio Galán" },
  { label: "Junín", value: "Junín" },
  { label: "La Candelaria", value: "La Candelaria" },
  { label: "La Campiña", value: "La Campiña" },
  { label: "La Castellana", value: "La Castellana" },
  { label: "La Concepción", value: "La Concepción" },
  { label: "La Consolata", value: "La Consolata" },
  { label: "La Esmeralda 1", value: "La Esmeralda 1" },
  { label: "La Esmeralda 2", value: "La Esmeralda 2" },
  { label: "La Esperanza", value: "La Esperanza" },
  { label: "La Floresta", value: "La Floresta" },
  { label: "La Florida", value: "La Florida" },
  { label: "La Gloria", value: "La Gloria" },
  { label: "La María", value: "La María" },
  { label: "La Matuna", value: "La Matuna" },
  { label: "La Paz", value: "La Paz" },
  { label: "La Plaza", value: "La Plaza" },
  { label: "La Providencia", value: "La Providencia" },
  { label: "La Quinta", value: "La Quinta" },
  { label: "La Sierrita", value: "La Sierrita" },
  { label: "La Troncal", value: "La Troncal" },
  { label: "Laguito", value: "Laguito" },
  { label: "Las Américas", value: "Las Américas" },
  { label: "Las Brisas", value: "Las Brisas" },
  { label: "Las Delicias", value: "Las Delicias" },
  { label: "Las Gaviotas", value: "Las Gaviotas" },
  { label: "Las Palmas", value: "Las Palmas" },
  { label: "Las Palmeras", value: "Las Palmeras" },
  { label: "Libertador", value: "Libertador" },
  { label: "Lo Amador", value: "Lo Amador" },
  { label: "Los Almendros", value: "Los Almendros" },
  { label: "Los Ángeles", value: "Los Ángeles" },
  { label: "Los Calamares", value: "Los Calamares" },
  { label: "Los Caracoles", value: "Los Caracoles" },
  { label: "Los Cerros", value: "Los Cerros" },
  { label: "Los Comuneros", value: "Los Comuneros" },
  { label: "Los Corales", value: "Los Corales" },
  { label: "Los Ejecutivos", value: "Los Ejecutivos" },
  { label: "Los Jardines", value: "Los Jardines" },
  { label: "Los Laureles", value: "Los Laureles" },
  { label: "Los Santanderes", value: "Los Santanderes" },
  { label: "Loma Fresca", value: "Loma Fresca" },
  { label: "Luis Carlos Galán", value: "Luis Carlos Galán" },
  { label: "Manga", value: "Manga" },
  { label: "Marbella", value: "Marbella" },
  { label: "María Cano", value: "María Cano" },
  { label: "Martínez Martelo", value: "Martínez Martelo" },
  { label: "Mirador de Nuevo Bosque", value: "Mirador de Nuevo Bosque" },
  { label: "Nariño", value: "Nariño" },
  { label: "Nelson Mandela", value: "Nelson Mandela" },
  { label: "Nuevo Bosque", value: "Nuevo Bosque" },
  { label: "Nuevo Paraíso", value: "Nuevo Paraíso" },
  { label: "Nuevo Porvenir", value: "Nuevo Porvenir" },
  { label: "Nueve de Abril", value: "Nueve de Abril" },
  { label: "Olaya Herrera", value: "Olaya Herrera" },
  { label: "Palestina", value: "Palestina" },
  { label: "Pablo VI 1", value: "Pablo VI 1" },
  { label: "Pablo VI 2", value: "Pablo VI 2" },
  { label: "Paraíso", value: "Paraíso" },
  { label: "Paraguay", value: "Paraguay" },
  { label: "Parque Heredia", value: "Parque Heredia" },
  { label: "Pedro Salazar", value: "Pedro Salazar" },
  { label: "Petare", value: "Petare" },
  { label: "Piedra de Bolívar", value: "Piedra de Bolívar" },
  { label: "Pie de la Popa", value: "Pie de la Popa" },
  { label: "Pie del Cerro", value: "Pie del Cerro" },
  { label: "Policarpa", value: "Policarpa" },
  { label: "Puerta de Hierro", value: "Puerta de Hierro" },
  { label: "R. del Caribe", value: "R. del Caribe" },
  { label: "República de Chile", value: "República de Chile" },
  { label: "República de Venezuela", value: "República de Venezuela" },
  { label: "República del Caribe", value: "República del Caribe" },
  { label: "República del Líbano", value: "República del Líbano" },
  { label: "San Bernardo", value: "San Bernardo" },
  { label: "San Bernardo de Asís", value: "San Bernardo de Asís" },
  { label: "San Diego", value: "San Diego" },
  { label: "San Fernando", value: "San Fernando" },
  { label: "San Francisco", value: "San Francisco" },
  { label: "San Isidro", value: "San Isidro" },
  { label: "San José de los Campanos", value: "San José de los Campanos" },
  { label: "San José Obrero", value: "San José Obrero" },
  { label: "San Pedro", value: "San Pedro" },
  { label: "San Pedro Mártir", value: "San Pedro Mártir" },
  { label: "San Pedro y Libertad", value: "San Pedro y Libertad" },
  { label: "Santa Clara", value: "Santa Clara" },
  { label: "Santa Lucía", value: "Santa Lucía" },
  { label: "Santa María", value: "Santa María" },
  { label: "Santa Mónica", value: "Santa Mónica" },
  { label: "Santillana de los Patios", value: "Santillana de los Patios" },
  { label: "Sectores Unidos", value: "Sectores Unidos" },
  { label: "Siete de Agosto", value: "Siete de Agosto" },
  { label: "Simón Bolívar", value: "Simón Bolívar" },
  { label: "Tacarigua", value: "Tacarigua" },
  { label: "Ternera", value: "Ternera" },
  { label: "Tesca Nuevo", value: "Tesca Nuevo" },
  { label: "Tesca Viejo", value: "Tesca Viejo" },
  { label: "Torices", value: "Torices" },
  { label: "Villa Estrella", value: "Villa Estrella" },
  { label: "Villa Hermosa", value: "Villa Hermosa" },
  { label: "Villa Rosita", value: "Villa Rosita" },
  { label: "Villa Rubia", value: "Villa Rubia" },
  { label: "Villa Sandra 1", value: "Villa Sandra 1" },
  { label: "Villa Sandra 2", value: "Villa Sandra 2" },
  { label: "Virgen del Carmen", value: "Virgen del Carmen" },
  { label: "Viejo Porvenir", value: "Viejo Porvenir" },
  { label: "Zaragocilla", value: "Zaragocilla" }
];
